## News Classification With ML in Julia
+ Aim: To Classify news feeds into their respective categories
+ Using News Feed from Reuters


In [1]:
# ED Packages
using DataFrames

In [2]:
# ML Packages
using ScikitLearn: fit!,fit_transform!,predict,@sk_import

In [3]:
# Load Dataset
df = readtable("NewsDataset.csv")

100×6 DataFrames.DataFrame
│ Row │ x  │
├─────┼────┤
│ 1   │ 0  │
│ 2   │ 1  │
│ 3   │ 2  │
│ 4   │ 3  │
│ 5   │ 4  │
│ 6   │ 5  │
│ 7   │ 6  │
│ 8   │ 7  │
│ 9   │ 8  │
│ 10  │ 9  │
│ 11  │ 10 │
⋮
│ 89  │ 88 │
│ 90  │ 89 │
│ 91  │ 90 │
│ 92  │ 91 │
│ 93  │ 92 │
│ 94  │ 93 │
│ 95  │ 94 │
│ 96  │ 95 │
│ 97  │ 96 │
│ 98  │ 97 │
│ 99  │ 98 │
│ 100 │ 99 │

│ Row │ Title                                                                                             │
├─────┼───────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 1   │ "Bank stocks lead Wall Street lower amid Syria tensions, Russia trade threat"                     │
│ 2   │ "Trade war backfire: Steel tariff shrapnel hits U.S. farmers"                                     │
│ 3   │ "U.S. bank executives see delayed boost from tax overhaul"                                        │
│ 4   │ "Wells Fargo faces \$1 billion fine from loan abuses"                                              │
│ 5   │ "Musk insists Tesla does not need more capital, predicts profit soon"                             │
│ 6   │ "Bratz maker's CEO bids \$890 million for Toys 'R' Us stores"                                      │
│ 7   │ "JPMorgan profit just below estimates on weak investment banking"                                 │
│ 8   │ "Wells Fargo CFO says government, not banks, should set gun policy"                               │
│ 9   │ "Citigroup profit beats on strength in consumer banking, equity trading"                          │
│ 10  │ "Trump orders review of U.S. Postal Service following criticism of Amazon"                        │
│ 11  │ "Motor racing: Hamilton fastest in China practice but Ferrari close"                              │
⋮
│ 89  │ "Religious faith linked to suicidal behavior in LGBQ adults"                                      │
│ 90  │ "Patients more satisfied when doctors treat fewer people"                                         │
│ 91  │ "Trump's personal lawyer attacked by U.S. prosecutor over privacy claim"                          │
│ 92  │ "Trump, called an unethical liar in book, blasts ex-FBI chief as 'slime ball'"                    │
│ 93  │ "Trump says U.S. will only rejoin Pacific trade pact if terms are improved"                       │
│ 94  │ "With Russia on his mind, Trump looks for tougher approach on Syria: sources"                     │
│ 95  │ "Republican-led House panel orders interviews with Pruitt aides at EPA"                           │
│ 96  │ "Trump to lift legal threat to states that permit marijuana use"                                  │
│ 97  │ "Ex-FBI deputy director faulted by Justice Department on media disclosure"                        │
│ 98  │ "Trump lawyer arranged \$1.6 million payoff to Playboy Playmate for Republican fundraiser: source" │
│ 99  │ "Special counsel has evidence Michael Cohen traveled to Prague: McClatchy"                        │
│ 100 │ "House passes bill to streamline 'Volcker Rule'"                                                  │

│ Row │ Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

In [4]:
# size nrow ncol
size(df)

(100, 6)

In [5]:
# Columns
names(df)

6-element Array{Symbol,1}:
 :x                
 :Title            
 :Description      
 :Short_description
 :Category         
 :CategoryID       

In [6]:
showcols(df)

100×6 DataFrames.DataFrame
│ Col # │ Name              │ Eltype │ Missing │
├───────┼───────────────────┼────────┼─────────┤
│ 1     │ x                 │ Int64  │ 0       │
│ 2     │ Title             │ String │ 0       │
│ 3     │ Description       │ String │ 0       │
│ 4     │ Short_description │ String │ 0       │
│ 5     │ Category          │ String │ 0       │
│ 6     │ CategoryID        │ Int64  │ 0       │

In [7]:
#  checking Missing NA
isna.(df)

false

### Feature Extraction

In [8]:
# Vectorization 
@sk_import feature_extraction.text: CountVectorizer
vectorizer = CountVectorizer()

PyObject CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [9]:
corpus = df[:Short_description]

100-element DataArrays.DataArray{String,1}:
 "Financial stocks led a drop on Wall Street on Friday, as results from big banks failed to enthuse and geopolitical tensions in Syria and Russia further unnerved investors."                                                                                                                                         
 "Lucas Strom, who runs a century-old family farm in rural Illinois, canceled an order to buy a new \$71,000 grain storage bin last month - after the seller raised the price 5 percent in a day."                                                                                                                     
 "Banks have not reaped the full benefit of U.S. tax cuts, Wall Street executives said on Friday after a string of quarterly results, with expected business growth and higher consumer spending yet to materialize."                                                                                                  
 "Two U.S. regulator

In [10]:
X = fit_transform!(vectorizer,corpus)

PyObject <100x1157 sparse matrix of type '<type 'numpy.int64'>'
	with 3020 stored elements in Compressed Sparse Row format>

In [11]:
y = convert(Array,df[:CategoryID])

100-element Array{Int64,1}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 1
 1
 1
 ⋮
 3
 3
 4
 4
 4
 4
 4
 4
 4
 4
 4
 4

In [12]:
# Split Data
@sk_import model_selection: train_test_split

PyObject <function train_test_split at 0x7ff6c4030320>

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

4-element Array{Any,1}:
 PyObject <80x1157 sparse matrix of type '<type 'numpy.int64'>'
	with 2398 stored elements in Compressed Sparse Row format>
 PyObject <20x1157 sparse matrix of type '<type 'numpy.int64'>'
	with 622 stored elements in Compressed Sparse Row format> 
 [0, 3, 2, 4, 2, 1, 4, 4, 0, 1  …  4, 1, 3, 3, 2, 2, 1, 1, 4, 0]                                                           
 [3, 0, 1, 4, 4, 3, 2, 3, 1, 0, 1, 3, 1, 3, 4, 0, 1, 1, 1, 3]                                                              

### Model Building

In [14]:
# Using Naive Bayes
@sk_import naive_bayes: MultinomialNB

PyObject <class 'sklearn.naive_bayes.MultinomialNB'>

In [15]:
model = MultinomialNB()
fit!(model, X_train, y_train)

PyObject MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [16]:
## Checking The Accuracy of Our Model
accuracy = sum(predict(model, X_train) .== y_train) / length(y_train)
println("Accuracy of model for Training: $accuracy")

Accuracy of model for Training: 0.9375


In [17]:
## Checking The Accuracy of Our Model
accuracy = sum(predict(model, X_test) .== y_test) / length(y_test)
println("Accuracy of model for Test Data: $accuracy")

Accuracy of model for Test Data: 0.65


In [18]:
predict(model,X_test)

20-element Array{Int64,1}:
 4
 0
 1
 4
 4
 2
 2
 0
 1
 0
 2
 3
 1
 3
 4
 2
 4
 1
 1
 4